app_blog/urls.py
from django.conf.urls import url
from views import homepage
from .views.homepage import HomepageHandler
from .views.newpost import NewpostHandler
from .views.blogEntry import BlogEntryHandler
from .views.signup import SignupHandler
from .views.signin import SigninHandler
from .views.signout import SignoutHandler
from .views.profile import ProfileHandler
from .views.editProfile import EditProfileHandler

# namespace for our blog app
app_name = 'app_blog'

# map urls to their view handlers
urlpatterns = [
    url(r'^$', HomepageHandler.as_view(), name='homepage'),
    url(r'^newpost$',NewpostHandler.as_view(), name='newpost'),
    url(r'^blog_entry/(?P<blog_id>[0-9]{1,100})$', BlogEntryHandler.as_view(), name='blog_entry'),
    url(r'^signup$', SignupHandler.as_view(), name='signup'),
    url(r'^signin$', SigninHandler.as_view(), name='signin'),
    url(r'^signout$', SignoutHandler.as_view(), name='signout'),
    url(r'^author/(?P<username>[a-zA-Z0-9_-]{3,20})/$', ProfileHandler.as_view(), name='profile'),
    url(r'^author/(?P<username>[a-zA-Z0-9_-]{3,20})/edit_profile/$', EditProfileHandler.as_view(), name='edit_profile'),
]

myblogger/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app_blog.urls')),
]

app_blog/models.py
'''
All DB model classes are defined here
'''
from __future__ import unicode_literals
from django.db import models
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django import forms

# A blog post
class Blog(models.Model):
    blog_title = models.CharField(max_length=200)
    blog_abstract = models.TextField()
    blog_content = models.TextField()
    pub_date = models.DateTimeField('date published')
    # create Many-to-One relationship with a Profile model
    submitter = models.ForeignKey('Profile', on_delete=models.CASCADE, null=True)

# Profile model associated with Django's 'User' model object
class Profile(models.Model):
    # Create relationship with 'User' model
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    biography = models.TextField(max_length=200)
    profile_name = models.CharField(max_length=48)
    occupation = models.CharField(max_length=48)
    employment = models.CharField(max_length=48)

    # Profile will be created/updated in accordance with the User it's related to
    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

app_blog/forms/newpostForm.py
'''
A form instance to be used in the newpost page
'''
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django import forms

class NewpostForm(forms.Form):
    blog_title = forms.CharField(max_length=64)
    blog_abstract = forms.CharField(widget=forms.Textarea(attrs={
                                    'cols': 10, 'rows': 5,
                                    'placeholder': 'your blog summary'
                                    }), max_length=128)
    blog_content = forms.CharField(widget=forms.Textarea, max_length=500)

app_blog/forms/profileForm.py
'''
A form instance to be used in the signin page
'''
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django import forms

class ProfileForm(forms.Form):
    name = forms.CharField(label='', max_length=48, required=False)
    occupation = forms.CharField(label='', max_length=48, required=False)
    employment = forms.CharField(label='', max_length=48, required=False)
    biography = forms.CharField(widget=forms.Textarea, required=False)

app_blog/forms/signinForm.py
'''
A form instance to be used in the signin page
'''
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django import forms

class SigninForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
                              'placeholder': 'your username'
                              }), label='', max_length=32)

    password = forms.CharField(widget=forms.PasswordInput(attrs={
                               'placeholder':'your password'
                               }), max_length=32)

app_blog/forms/signupForm.py
'''
A form instance to be used in the signup page
'''
from django.contrib.auth.models import User
from django import forms

class SignupForm(forms.Form):
    username = forms.CharField(label='', max_length=32)
    password = forms.CharField(widget=forms.PasswordInput(), max_length=32)
    verify_password = forms.CharField(widget=forms.PasswordInput(), max_length=32)
    email = forms.EmailField(max_length=32)

    # add custom form validation
    def clean(self):
        # retrieve user input
        cleaned_data = super(SignupForm, self).clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')
        verify_password = cleaned_data.get('verify_password')

        # check if username is available
        if User.objects.filter(username=username).exists():
            # add 'error' to the 'username' field
            self.add_error('username', "username is taken!")

        # check if password and 2nd entry match
        if password and verify_password:
            if password != verify_password:
                # add 'error' to the 'password' field
                self.add_error('verify_password', "passwords don't match!")

app_blog/views/baseView.py
'''
BaseView is the base view handler: all view classes subclass this
'''
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.template import loader
from django.views import View

class BaseView(View):
    # writes plain text to page
    # @content: plain text to write to page
    def write(self, content):
        return HttpResponse(content)

    # renders a template to page
    # @template_name: name of the template file
    # @temp_context: template variable-value mapping
    def render_template(self, request, template_name, temp_context):
        template = loader.get_template('app_blog/%(template_name)s'%{
                                       'template_name':template_name
                                       })
        return HttpResponse(template.render(temp_context, request))

    # redirect to the specified url
    # @rurl: the url to redirect to
    def redirect(self, rurl):
        return HttpResponseRedirect(rurl)

    # renders a 404 error page
    def render_404(self, request, error_msg="The page you're looking for doesn't exist!"):
        return self.render_template(request, 'error404.html', {'error_msg':error_msg})

app_blog/views/blogEntry.py
'''
View Controller class for the blog permalink page
'''
from baseView import BaseView
from app_blog.models import Blog

class BlogEntryHandler(BaseView):
    def get(self, request, blog_id):
        # retrieve blog and show if exists
        try:
            blog = Blog.objects.get(id=blog_id)
        except Blog.DoesNotExist:
            return self.render_404(request)
        # blog exists => show it
        return self.render_template(request, 'blogEntry.html', {'blog':blog})

app_blog/views/editProfile.py
'''
View controller class for the 'edit profile' page
'''
from baseView import BaseView
from app_blog.forms.profileForm import ProfileForm

class EditProfileHandler(BaseView):
    def get(self, request, username):
        # create the submission form and render it
        form = ProfileForm()
        return self.render_template(request, 'edit_profile.html', {
                                    'user': request.user,
                                    'form': form
                                    })

    def post(self, request, username):
        # get user form submission
        userForm = ProfileForm(request.POST.copy())
        # save changes if valid submission
        if userForm.is_valid():
            self.updateUserProfile(userForm)
        # if invalid, show errors
        return self.redirect('/author/%(username)s' % {'username': username})

    # helper function to update user profile fields
    def updateUserProfile(self, userForm):
        # retrieve submission data
        name = userForm.cleaned_data['name']
        occupation = userForm.cleaned_data['occupation']
        employment = userForm.cleaned_data['employment']
        biography = userForm.cleaned_data['biography']
        modified = False
        # update user profile fields
        if name:
            self.request.user.profile.profile_name = name
            modified = True
        if occupation:
            self.request.user.profile.occupation = occupation
            modified = True
        if employment:
            self.request.user.profile.employment = employment
            modified = True
        if biography:
            self.request.user.profile.biography = biography
            modified = True

        # save to DB only if 1 or more fields were changed
        if modified:
            self.request.user.save()

app_blog/views/homepage.py
'''
View Controller class for the home page
'''
from baseView import BaseView
from app_blog.utility import utils

class HomepageHandler(BaseView):
    def get(self, request):
        # get the last 10 blogs
        blogs = utils.getBlogs(10)
        return self.render_template(request, 'homepage.html', {
                                    'user': request.user,
                                    'blogs':blogs
                                    })

app_blog/views/newpost.py
'''
View Controller class for the new blog submission page
'''
from baseView import BaseView
from app_blog.forms.newpostForm import NewpostForm
from django.utils import timezone

class NewpostHandler(BaseView):
    def get(self, request):
        # 'post submission' only allowed for logged in user
        if request.user.is_authenticated():
            userForm = NewpostForm()
            return self.render_template(request, 'newpost.html', {'form':userForm})
        # if not logged in, redirect to homepage
        else:
            return self.redirect('/')

    def post(self, request):
        # retrieve user submission
        userForm = NewpostForm(request.POST.copy())
        # save form if valid
        if userForm.is_valid():
            blog_entry = self.saveForm(userForm)
            # redirect to blog permalink page
            return self.redirect('/blog_entry/%(blog_id)s'%{'blog_id': str(blog_entry.id)})
        # else user will be shown errors
        else:
            return self.render_template(request, 'newpost.html', {'form':userForm})

    # creates a blog entry for the user and returns the new 'blog' model object
    def saveForm(self, userForm):
        # retrieve submission data
        title = userForm.cleaned_data['blog_title']
        abstract = userForm.cleaned_data['blog_abstract']
        content = userForm.cleaned_data['blog_content']
        # create a 'blog entry' for the logged in user
        blog_entry = self.request.user.profile.blog_set.create(blog_title=title,
                                     blog_abstract=abstract,
                                     blog_content=content,
                                     pub_date=timezone.now())
        return blog_entry

app_blog/views/profile.py
'''
View Controller class for user profile page
handles views for:
    1. logged in user's profile
    2. other users' profile
'''

from baseView import BaseView
from django.contrib.auth.models import User
from app_blog.utility import utils

class ProfileHandler(BaseView):
    def get(self, request, username):
        # user visiting own profile
        if self.request.user.is_authenticated() and username == self.request.user.get_username():
            # get logged in user's last 10 blog submissions
            blogs = utils.getBlogsForUser(request.user, 10)
            return self.render_template(request, 'profile.html', {
                                        'user': request.user,
                                        'blogs': blogs
                                        })
        # user visiting another user's profile
        elif utils.userExists(username):
            # get the user
            user = utils.getUserByUsername(username)
            # get username's last blogs
            blogs = utils.getBlogsForUser(user, 10)
            if user:
                return self.render_template(request, 'author.html',
                                                {'author':user,
                                                 'blogs': blogs
                                                })
        # invalid request
        # can get here if requested 'username' is invalid
        else:
            return self.render_404(request)

app_blog/views/signin.py
'''
View Controller class for the signin page
'''
from django.contrib.auth import authenticate, login
from app_blog.forms.signinForm import SigninForm
from baseView import BaseView

class SigninHandler(BaseView):
    def get(self, request):
        # redirect to homepage if user already logged in
        if request.user.is_authenticated():
            return self.redirect('/')
        # show signin page if no logged in user found
        return self.render_template(request, 'signin.html', {'form': SigninForm()})

    def post(self, request):
        # retrieve user input
        userForm = SigninForm(request.POST.copy())

        # make sure fields are filled in
        if userForm.is_valid():
            username = userForm.cleaned_data['username']
            password = userForm.cleaned_data['password']
            # authenticate user credentials
            user = authenticate(username=username, password=password)
            # log user in if authentication is successful
            if user:
                login(request, user)
                return self.redirect('/author/%(username)s' % {'username': user.username})
            # show error messages on authentication failure
            else:
                return self.render_template(request, 'signin.html',
                                            {'form':userForm,
                                            'signin_error':'username or password wrong'
                                            })
        # shouldn't get here since submission is not allowed if fields are empty
        else:
            return self.render_template(request, 'signin.html',
                                        {'form':userForm,
                                        'signin_error':'username or password wrong'
                                        })

app_blog/views/signout.py
'''
View Controller class for the sign out page
'''
from django.contrib.auth import logout
from baseView import BaseView

class SignoutHandler(BaseView):
    def get(self, request):
        # deletes session, cookies
        logout(request)
        # redirect to home page
        return self.redirect('/')

app_blog/views/signup.py
'''
View Controller class for the sign up page
'''
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from baseView import BaseView
from app_blog.forms.signupForm import SignupForm

class SignupHandler(BaseView):
    def get(self, request):
        # redirect to homepage if user already logged in
        if request.user.is_authenticated():
            return self.redirect('/')
        # show signup page
        return self.render_template(request, 'signup.html', {'form':SignupForm()})

    def post(self, request):
        # create a form instance and populate it with data from request
        userForm = SignupForm(request.POST.copy())
        if userForm.is_valid():
            # create a user if valid submission
            newUser = self.saveUser(userForm)
            if newUser:
                login(request, newUser)
                return self.redirect('/author/%(username)s'% {'username': newUser.username})
            else:
                self.render_404("login failed")
        # if form is invalid, show errors
        else:
            return self.render_template(request, 'signup.html', {'form':userForm})

    # saves user to the DB
    def saveUser(self, userForm):
        username = userForm.cleaned_data['username']
        password = userForm.cleaned_data['password']
        email = userForm.cleaned_data['email']
        
        newUser = User.objects.create_user(username, email, password)
        newUser.profile.profile_name = username
        newUser.save()
        user = authenticate(username=username, password=password)
        return user

app_blog/templates/app_blog/author.html
{% extends 'app_blog/base.html' %}

{% block head %}
    <!-- import parent's content-->
    {{ block.super }}
    {% load static %}
    <link rel='stylesheet' type='text/css' href="{% static 'author.css' %}">
{% endblock %}

<!-- use header provided by base -->
{% block header %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <div id="main-container">
        <!--Profile Information-->
        <div id='profile'>
            <!-- avatar, name, occupation-->
            <div id='profile-pane1'>
                <img src="{% static 'images/saitama.jpg' %}" id="profile-img">
                <div id="profile-details">
                    <h2 id="profile-username">{{author.profile.profile_name}}</h2>
                    {% if author.profile.occupation and author.profile.employment%}
                    <h4 id="user-info">{{author.profile.occupation}}, {{author.profile.employment}} </h4>
                    {% elif author.profile.occupation %}
                        <h4 id="user-info">{{author.profile.occupation}}</h4>
                    {% elif author.profile.employement %}
                        <h4 id="user-info">{{author.profile.employment}}</h4>
                    {% endif %}
                </div>
            </div>

            <!--Author biography goes here-->
            <div id='profile-pane2'>
                {% if author.profile.biography %}
                    <p>
                        {{author.profile.biography}}
                    </p>
                {% endif %}
            </div>
        </div>

        <!-- user submission history-->
        <div id="page-subtitle">
            <!-- title of the second pane-->
            <h3>
                Submission History
            </h3>
        </div>
        <hr style="width:70%;">

        <!-- container of rows of submitted blog posts -->
        <div>
            {% if blogs %}
                {% for blog in blogs %}
                    <div class="row">
                        <div>
                            <h3 class='blog-title'>
                                {{blog.blog_title}}
                            </h3>
                            <h4>created at {{blog.pub_date}}</h4>
                            <!-- abstract text of the blog post-->
                            <div>
                                <pre>{{blog.blog_content}}</pre>
                            </div>
                            <hr>
                        </div>
                    </div>
                {% endfor %}
            {% else %}

            <!--message shown if user has no blogs submitted-->
            <div class='display-msg-container'>
                <h3>
                    Nothing....
                </h3>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

app_blog/templates/app_blog/base.html
<!-- parent template of all page templates -->
<!DOCTYPE html>
<html>
    <head>
        {% block head %}
            <meta charset='utf-8'>
            <meta http-equiv='X-UA-Compatible' content='IE-edge'>
            <meta name='viewport' content='width=device-width, initial-scale=1'>
            <title>Blogzzz</title>
            <link href="https://fonts.googleapis.com/css?family=Lato:100,300" rel="stylesheet">
            {% load static %}
            <link rel='stylesheet' href="{% static 'bootstrap/css/bootstrap.css' %}">
            <link rel='stylesheet' type='text/css' href="{% static 'base.css' %}">
        {% endblock %}
    </head>
    <body>
        <div id="header-container">
            <header>
                {% block header %}
                <div class='container-fluid'>
                    <div class='row'>
                        <!-- page title-->
                        <div class='col-xs-8 col-sm-8 col-md-8' id="title-header">
                            <h1 class="text-left text-super">
                                <a href="{% url 'app_blog:homepage' %}">
                                    BLOGzzz
                                </a>
                            </h1>
                        </div>
                        {% if user.is_authenticated %}
                            <!-- Sign Out button-->
                            <div class='col-xs-4 col-sm-4 col-md-2 btn-header'>
                                <a href="{% url 'app_blog:signout' %}">
                                    <span>Sign Out</span>
                                </a>
                            </div>
                            <!-- my profile button-->
                            <div class='col-xs-4 col-sm-4 col-md-2 btn-header'>
                                <a href="{% url 'app_blog:profile' user.username %}">
                                    <span>My Profile</span>
                                </a>
                            </div>
                        {% else %}
                            <!-- Sign In button-->
                            <div class='col-xs-4 col-sm-4 col-md-4 btn-header'>
                                <a href="{% url 'app_blog:signin' %}">
                                    <span>Sign in</span>
                                </a>
                            </div>
                        {% endif %}
                        </div>
                    </div> <!-- row-->
                </div> <!-- container-->
                {% endblock%}
            </header>
        </div>
        <!-- area for the derived html to post content-->
        <div id='main-content'>
            {% block content%}
            {% endblock %}
        </div>
    </body>
</html>

app_blog/templates/app_blog/blogEntry.html
{% extends 'app_blog/base.html' %}
<!-- add additional info to head-->
{% block head %}
    {{ block.super }}
    {% load static %}
    <link rel='stylesheet' type='text/css' href="{% static 'blogEntry.css' %}">
{% endblock %}

<!-- use header provided by base -->
{% block header %}
    {{ block.super }}
{% endblock %}

<!-- Fill the actual page content -->
{% block content %}
    {% if blog %}
    <div id="container-blog">
        <h1 id='blog-title'>
            {{blog.blog_title}}
        </h1>
        <hr>

        <!-- submitter info on the blog post entry-->
        <div class="profile-area">
            <img src="{% static 'images/saitama.jpg' %}" class="img-profile">
            <div>
                <h4 class="username-profile">
                    <a href="{% url 'app_blog:profile' blog.submitter.user.username%}">
                        {{blog.submitter.profile_name}}
                    </a>
                </h4>
                <h4 class="date-profile">{{blog.pub_date}}</h4>
            </div>
        </div>

        <!-- Blog content -->
        <div class='container-content'>
            <pre>{{blog.blog_content}}</pre>
        </div>
    </div>
    {% endif %}
{% endblock %}

app_blog/templates/app_blog/error404.html
{% extends 'base.html' %}
<!-- add additional info to head-->
{% block head %}
    {{ super() }}
    <link rel='stylesheet' type='text/css' href='static/error404.css'>
{% endblock %}

<!-- use header provided by base -->
{% block header %}
    {{ super() }}
{% endblock %}

<!-- Add own page content -->
{% block content %}
    <div id='error-msg'>
        <h3 class='text-super'>Sorry, that page doesn't exist!</h3>
    </div>
{% endblock %}

app_blog/templates/app_blog/home.html
{% extends 'app_blog/base.html' %}
<!-- add additional info to head-->
{% block head %}
    {{ block.super }}
    <link rel='stylesheet' type='text/css' href='static/front.css'>
{% endblock %}

<!-- use header provided by base -->
{% block header %}
    {{ block.super }}
{% endblock %}

<!-- Add own page content -->

app_blog/templates/app_blog/homepage.html
{% extends 'app_blog/base.html' %}
<!-- add additional info to head-->
{% block head %}
    {{ block.super }}
    {% load static %}
    <link rel='stylesheet' type='text/css' href="{% static 'front.css' %}">
{% endblock %}

<!-- use header provided by base -->
{% block header %}
    {{ block.super }}
{% endblock %}

<!-- Add own page content -->
{% block content %}
    {% if blogs %}
        <div class="container-fluid container-main">
            <div class="row">
                <!-- leave some space for ad-->
                <div class="col-xs-8 col-md-8 container-blogs">
                    {% for blog in blogs %}
                        <div class='row'>
                            <div class='col-md-10'>

                                <!-- title of the blog post -->
                                <h3 class='blog-title'>
                                    <a href="{% url 'app_blog:blog_entry' blog.id %}">
                                        {{blog.blog_title}}
                                    </a>
                                </h3>

                                <!-- submitter info on the blog post entry-->
                                <div class="profile-area">
                                    <img src="{% static 'images/saitama.jpg' %}" class="img-profile">
                                    <div>
                                        <h4 class="username-profile">
                                            <a href="{% url 'app_blog:profile' blog.submitter.user.username %}">
                                                {{blog.submitter.profile_name}}
                                            </a>
                                        </h4>
                                        <h4 class="date-profile">{{blog.pub_date}}</h4>
                                    </div>
                                </div>

                                <!-- abstract text of the blog post-->
                                <div class='container-content'>
                                    <pre>{{blog.blog_abstract}}</pre>
                                </div>

                            </div>
                        </div>
                        <!-- the line separating blog posts -->
                        <hr>

                    {% endfor %}
                </div>
            </div>
        </div>
    <!--Display message when there are no blog posts-->
    {% else %}
        <div class="display-msg">
            <h3 class="text-super">
                Be the first blogger!
            </h3>
        </div>
    {% endif %}
{% endblock %}

app_blog/templates/app_blog/profile.html
{% extends 'app_blog/base.html' %}

{% block head %}
    <!-- import parent's content-->
    {{ block.super }}
    <title>Welcome</title>
    {% load static %}
    <link rel='stylesheet' type='text/css' href="{% static 'profile.css' %}">
{% endblock %}

<!-- use header provided by base -->
{% block header %}
<div class='container-fluid'>
    <div class='row'>
        <!-- page title-->
        <div class='col-xs-6 col-sm-6 col-md-8' id="title-header">
            <h1 class="text-left text-super">
                <a href="{% url 'app_blog:homepage' %}">
                    BLOGzzz
                </a>
            </h1>
        </div>
            <!-- Sign Out button-->
            <div class='col-xs-6 col-sm-3 col-md-2 btn-header'>
                <a href="{% url 'app_blog:signout' %}">
                    <span>Sign Out</span>
                </a>
            </div>
            <!-- my profile button-->
            <div class='col-xs-6 col-sm-3 col-md-2 btn-header'>
                <a href="{% url 'app_blog:edit_profile' user.username %}">
                    <span>Edit Profile</span>
                </a>
            </div>
        </div>
    </div> <!-- row-->
</div> <!-- container-->
{% endblock %}

{% block content %}
    <!-- first pane: welcome user-->
    <div class="container-fluid">
        <div class="row container-welcome">
            <h1 id='text-welcome'>Welcome {{user.profile.profile_name}}</h1>
            <div id='btn-newpost'>
                <!-- newpost link button -->
                <a href="{% url 'app_blog:newpost' %}">
                    <span>write new post</span>
                </a>
            </div>
        </div>
    </div>

    <!-- second pane: user submission history-->
    <div id="title-history-container">
        <!-- title of the second pane-->
        <h3>
            Your Submission History
        </h3>
    </div>
    <hr style="width:70%;">
    <!-- container of rows of submitted blog posts -->
    <div id="blogs-container">
        {% if blogs %}
            {% for blog in blogs %}
                <div class="row">
                    <div>
                        <h3 class='blog-title'>
                            {{blog.blog_title}}
                        </h3>
                        <h4>created at {{blog.pub_date}}</h4>
                        <!-- abstract text of the blog post-->
                        <div class='content-container'>
                            <pre>{{blog.blog_content}}</pre>
                        </div>
                        <hr>
                    </div>
                </div>
            {% endfor %}
        {% else %}

        <!--message shown if user has no blogs submitted-->
        <div class='display-msg'>
            <h3>
                Nothing....
            </h3>
        </div>
        {% endif %}
    </div>
{% endblock %}

app_blog/templates/app_blog/signin.html
{% extends 'app_blog/base.html' %}

{% block head %}
    <!-- import parent's content-->
    {{ block.super }}
    <!-- add additional info to head-->
    <title>Sign In</title>
    <link rel='stylesheet' type='text/css' href='static/signin.css'>
{% endblock %}

<!-- use custom header for sign-in and sign-up pages -->
{% block header %}
    {% include 'app_blog/registration_header.html' %}
{% endblock %}

<!-- Add own page content -->
{% block content %}
    <!-- Sign In box-->
    <div class="container-panel">

        <!-- title : 'Sign In'-->
        <div class="title-container">
            <h1>Sign In</h1>
        </div>

        <!-- Sign In form -->
        <form method='post'>
            {% csrf_token %}
            <h3 class="form-title">
                username
            </h3>
            {{ form.username }}
            <label class="error-msg">
                {{ form.username.errors.as_text }}
            </label>

            <h3 class="form-title">
                password
            </h3>
            {{ form.password }}
            <br>
            <label class="error-msg">
                {{ form.password.errors }}
                {{ signin_error }}
            </label>
            <br>
            <br>
            <input type='submit' class="btn" value='Sign In'>
        </form>

        <!-- Sign Up button-->
        <div id="signup-container">
            <h4 class="form-comment">
                Don't have an account?
            </h4>
            
            <div id='btn-signup-container'>
                <a href="{% url 'app_blog:signup' %}">
                    <span>Sign Up</span>
                </a>
            </div>
        </div>

    </div>
{% endblock %}